import { Image } from "react-native";

export const imageSource = {
    greenLogo : require('../assets/icons/green-logo.png'),
    whiteLogo : require('../assets/icons/white-logo.png'),
    ChooseYourDoctor : require('../assets/images/chooseYourDoctor.png'),
    ScheduleYourAppointments: require('../assets/images/scheduleYourAppointments.png'),
    CheckYourMedicalHistory: require('../assets/images/checkYourMedicalHistory.png'),
    UseGoogle: require('../assets/icons/useGoogle.png'),
    UseFacebook: require('../assets/icons/useFacebook.png'),
    UseBiometrics: require('../assets/icons/useBiometrics.png'),
    ProfilePhoto: require('../assets/used-assets/photo.jpg'),
    Favorite: require('../assets/icons/favorite.png'),
    DoctorsIcon: require('../assets/icons/doctors.png'),
    PharmacyIcon: require('../assets/icons/pharmacy.png'),
    SpecialtiesIcon: require('../assets/icons/specialties.png'),
    RecordsIcon: require('../assets/icons/records.png'),
    CardiologyIcon: require('../assets/icons/cardiology.png'),
    DermatologyIcon: require('../assets/icons/dermatology.png'),
    GeneralMedicineIcon: require('../assets/icons/general-medicine.png'),
    GynecologyIcon: require('../assets/icons/gynecology.png'),
    OdontologyIcon: require('../assets/icons/odontology.png'),
    OncologyIcon: require('../assets/icons/oncology.png'),
    OphtamologyIcon: require('../assets/icons/ophtamology.png'),
    OrthopedicsIcon: require('../assets/icons/orthopedics.png'),
    MaleDoctor: require('../assets/images/maleDoctor.png'),
    FemaleDoctor: require('../assets/images/femaleDoctor.png'),
    HugeRecordIcon: require('../assets/icons/hugeRecordIcon.png'),
    AnalysisBigIcon: require('../assets/icons/analysis-Big.png'),
    VaccinationBigIcon: require('../assets/icons/vaccinations-Big.png'),
    MedicalHistoryBigIcon: require('../assets/icons/medicalHistory.png')
}